In [2]:
# array reshape 
#converting 1 dimensional array to 2 dimensional array 
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(6,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(1,6)
print(b)

[[1 2 3 4 5 6]]


In [7]:
# converting 1 dimensional array to 3 dimensional array
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3,1)
print(b)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [8]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2,1)
print(b)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [9]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(1,2,3)
print(b)

[[[1 2 3]
  [4 5 6]]]


In [10]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,1,3)
print(b)

[[[1 2 3]]

 [[4 5 6]]]
